version: "3.8"

services:
  node-app:
    build:
      context: ./server
    ports:
      - "5005:5005"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_SERVER_URL=http://node-app:5005
    depends_on:
      - node-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
